# Generated by Django 5.0.1 on 2024-02-07 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dosedashapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="products",
            new_name="product",
        ),
    ]
