# Generated by Django 5.0.1 on 2024-02-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dosedashapp", "0002_rename_products_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pPrice",
            field=models.PositiveIntegerField(),
        ),
    ]
