# Generated by Django 5.0.1 on 2024-02-07 04:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dosedashapp", "0003_alter_product_pprice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="pDescription",
            new_name="Product_Description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="pImage",
            new_name="Product_Image",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="pName",
            new_name="Product_Name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="pPrice",
            new_name="Product_Price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="pTag",
            new_name="Product_Tag",
        ),
    ]
