# Generated by Django 5.0.1 on 2024-02-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dosedashapp",
            "0004_rename_pdescription_product_product_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Product_Tag",
            field=models.CharField(max_length=200),
        ),
    ]
