# Generated by Django 5.0.1 on 2024-02-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dosedashapp", "0006_alter_reminder_reminder_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="Product_Tag",
        ),
        migrations.AddField(
            model_name="product",
            name="Product_Tag",
            field=models.ManyToManyField(blank=True, to="dosedashapp.producttag"),
        ),
    ]
