# Generated by Django 5.0.1 on 2024-02-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dosedashapp", "0007_producttag_remove_product_product_tag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Customer_Name", models.CharField(max_length=200)),
                ("Customer_Email", models.EmailField(max_length=200)),
                ("Customer_Message", models.TextField()),
            ],
        ),
    ]
