# Generated by Django 5.0.1 on 2024-03-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dosedashapp", "0009_product_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="Item_Pruchased",
            field=models.ManyToManyField(blank=True, to="dosedashapp.producttag"),
        ),
    ]
