# Generated by Django 5.0.1 on 2024-03-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dosedashapp", "0010_transaction_item_pruchased"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="Item_Pruchased",
            field=models.ManyToManyField(blank=True, to="dosedashapp.product"),
        ),
    ]
