# Generated by Django 5.0.1 on 2024-03-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dosedashapp", "0012_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="Address",
            new_name="Country",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="Area",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="City",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="Landmark",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="Province",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
