# Generated by Django 5.0.1 on 2024-03-02 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dosedashapp", "0014_transaction_item_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="Item_Quantity",
        ),
    ]
