# Generated by Django 5.0.1 on 2024-03-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dosedashapp", "0015_remove_transaction_item_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="Payment_Method",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
