# Generated by Django 5.0.1 on 2024-03-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosedashapp', '0018_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
