# Generated by Django 5.0.1 on 2024-03-11 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dosedashapp", "0019_category_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
